In [67]:
import numpy as np

persontype = np.dtype({'names':['name', 'chinese', 'math', 'english'],
                        'formats':['S32', 'i', 'i', 'i']})
peoples = np.array([("ZhangFei",68,65,30),("GuanYu",95,76,98), ("Liubei",98,86,88), 
                        ("DianWei",90,88,77),("XuZhu",80,90,90)], dtype=persontype)
names = peoples['name']
chineses = peoples['chinese']
maths = peoples['math']
englishs = peoples['english']

print(names)
print(chineses)
print(maths)
print(englishs)

# 统计数据
print(np.min(chineses))
print(np.min(maths))
print(np.min(englishs))

print(np.max(chineses))
print(np.max(maths))
print(np.max(englishs))

print(np.var(chineses))
print(np.var(maths))
print(np.var(englishs))

print(np.std(chineses))
print(np.std(maths))
print(np.std(englishs))

# 个人成绩求和
score_sum = np.add(chineses, maths)
score_sum = np.add(score_sum,englishs)
print(score_sum)

# 建立个人成绩数组
score_data = np.array([names,score_sum]) 
print(score_data)

# 按照成绩由大到小排序
score_data_sort = score_data[:,score_data[1].argsort()[::-1]]
print(score_data_sort)


[b'ZhangFei' b'GuanYu' b'Liubei' b'DianWei' b'XuZhu']
[68 95 98 90 80]
[65 76 86 88 90]
[30 98 88 77 90]
68
65
30
98
90
98
120.16
87.2
587.8399999999999
10.961751684835777
9.338094023943002
24.24541193710678
[163 269 272 255 260]
[[b'ZhangFei' b'GuanYu' b'Liubei' b'DianWei' b'XuZhu']
 [b'163' b'269' b'272' b'255' b'260']]
[[b'Liubei' b'GuanYu' b'XuZhu' b'DianWei' b'ZhangFei']
 [b'272' b'269' b'260' b'255' b'163']]
